language: ruby
rvm:
  - "2.5"
  - "2.6"
gemfile:
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.2.gemfile
env:
  - DB=mysql
  - DB=sqlite
matrix:
  allow_failures:
    # Allow 2.5 to fail until Travis CI bug is fixed. See:
    # * https://github.com/travis-ci/travis-ci/issues/8978
    # * https://github.com/travis-ci/travis-ci/issues/8969
    - rvm: "2.5"
before_script:
  - "cp spec/{.travis.,}database.yml"
  - "bundle exec rake db:prepare"
script: bundle exec rake spec
sudo: false
